FROM node:latest
WORKDIR /usr/src
COPY ./src/app .
COPY ./package*.json ./
RUN ["npm","install"]
CMD ["node","index.js"]

# WORKDIR /usr/src/app
# COPY . /usr/src/app
# COPY ./package*.json /usr/src/app
# RUN ["npm","install"]
# CMD ["nodemon","./src/app/index.js"]
