version: "3"

services:
 hello-service:
  build: .
  ports:
   - 3000:3000
  volumes:
   - ./src/app/index.js:/usr/src/index.js
  #  - ./package*.json:/usr/src
  #  - ./node_modules:/usr/src
