FROM node:latest
WORKDIR /usr/src
# RUN npm install -g nodemon
COPY . .
RUN ["npm","install"]
CMD ["node","server/index.js"]

# WORKDIR /usr/src/app
# COPY . /usr/src/app
# COPY ./package*.json /usr/src/app
# RUN ["npm","install"]
# CMD ["nodemon","./src/app/index.js"]
